version: '3.2'
services:
    node:
        container_name: trubbi
        entrypoint: /usr/aplication/start.sh
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/usr/aplication
        working_dir: /usr/aplication
        ports:
            - "3060:3000"
            - "9665:9662"
        networks:
            - trubbi-net
    mariadb:
        image: mariadb:10.8.3
        container_name: trubbi-mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=trubbi
            - MYSQL_DATABASE=trubbi
        volumes:
            - trubbi_db_volume:/var/lib/mysql
        ports:
            - 5004:3306
        networks:
          - trubbi-net 
    
    orion:
        image: fiware/orion
        hostname: orion
        container_name: fiware-orion
        ports:
            - "1026:1026"
        command: -dbhost mongodb -logLevel DEBUG -noCache
        networks:
            - trubbi-net  

    cygnus:
        image: fiware/cygnus-ngsi
        hostname: cygnus
        container_name: fiware-cygnus
        ports:
            - "5055:5055"
            - "5080:5080" 
        environment:
            - "CYGNUS_POSTGRESQL_HOST=postgres"
            - "CYGNUS_POSTGRESQL_PORT=5432"
            - "CYGNUS_POSTGRESQL_USER=postgres"
            - "CYGNUS_POSTGRESQL_PASS=password"
            - "CYGNUS_POSTGRESQL_DATABASE=postgres"
            - "CYGNUS_POSTGRESQL_ENABLE_CACHE=true"
            - "CYGNUS_POSTGRESQL_SERVICE_PORT=5055"
            - "CYGNUS_LOG_LEVEL=DEBUG"
            - "CYGNUS_SERVICE_PORT=5055"
            - "CYGNUS_API_PORT=5080"
        networks:
            - trubbi-net  

    mongodb:
        image: mongo:3.6
        container_name: mongodb
        hostname: mongodb
        ports:
            - "27017:27017" 
        command: --bind_ip_all --smallfiles
        volumes:
            - mongo_db_volume:/data
        networks:
            - trubbi-net  
      
    postgresdb:
        image: postgres
        hostname: postgres
        container_name: postgresdb
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_PASSWORD=password"
            - "POSTGRES_USER=postgres"
            - "POSTGRES_DB=postgres"
        volumes:
            - postgres_db_volume:/var/lib/postgresql/data
        networks:
            - trubbi-net  

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@ort.edu.ar}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - postgres_db_volume:/root/.pgadmin
        ports:
            - "4040:80"
        networks:
            - trubbi-net  
    adminmongo:
        image: mrvautin/adminmongo
        ports:
            - 1234:1234
        environment:
            - HOST=0.0.0.0
        networks:
            - trubbi-net  
    grafana:
        image: grafana/grafana-oss
        ports:
            - 3502:3000
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-clock-panel,grafana-worldmap-panel
        volumes:
            - grafana-storage:/var/lib/grafana #admin - ORT2022!
        networks:
            - trubbi-net  

networks:
  trubbi-net:
    name: trubbi-network

volumes:
    trubbi_db_volume:
    mongo_db_volume:
    postgres_db_volume:
    grafana-storage:
